name: Production Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted  # <--- CHANGED
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          # Since the runner is ON the server, we just run commands directly
          # Note: The runner creates its own work folder. 
          # You might want to copy files to your actual deployment folder or run docker directly here.

          docker compose -f docker-compose.prod.yml up --build -d
          docker image prune -f
